title: BeMain Dev
description: Young solo developer doing programming in my free time. Beyond coding, I love music, reading and roleplaying.
url: https://bemain.github.io/

theme: minima
minima:
  skin: auto
  # TODO: Fix social links, and add Google Play and App Store
  social_links:
    - { platform: github,  user_url: "https://github.com/BeMain" }

author: 
  name: Benjamin Agardh
  email: bemain.dev@gmail.com

