title: Musician's Toolbox
description: The all-in-one tool for musicians
url: https://bemain.github.io/

theme: minima
minima:
  skin: auto
  # TODO: Fix social links, and add Google Play and App Store
  social_links:
    - { platform: github,  user_url: "https://github.com/BeMain" }

header_pages:
  - privacy_policy.md

author: 
  name: Benjamin Agardh
  email: bemain.dev@gmail.com

