name: portfolio
description: "Benjamin Agardh's portfolio website"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.8

flutter:
  uses-material-design: true
  assets:
    - assets/projects/
