name: portfolio
description: "Benjamin Agardh's portfolio website"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    
  flutter_markdown: ^0.7.5
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  test: ^1.25.8

  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/projects/
    - assets/me/
    - assets/contact/
    - assets/writing/
